build: false
environment:
  global:
    db_class: 'Cake\Database\Driver\SqlServer'
    db_dsn: 'mysql:host=0.0.0.0;dbname=cakephp'
    db_database: 'cakephp'
    db_login: 'sa'
    db_password: 'Password12!'
  matrix:
    - PHP: "C:/PHP"
services:
  - mssql2008r2sp2
init:
  - SET PATH=C:\php\;%PATH%
install:
  - cd c:\
  - ps: Start-FileDownload 'http://robmorgan.s3.amazonaws.com/php55/php-5.5.7-nts-Win32-VC11-x86.zip'
  - 7z x php-5.5.7-nts-Win32-VC11-x86.zip -oc:\php
  - cd c:\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_sqlsrv.dll >> php.ini
  - echo extension=php_pdo_sqlsrv.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - cd C:\projects\cakephp
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar install
test_script:
  - sqlcmd -S ".\SQL2008R2SP2" -U sa -P Password12! -Q "create database cakephp;"
  - cd C:\projects\cakephp
  - "%PHP%/php.exe --version"
  - vendor\bin\phpunit.bat tests\TestCase\Database
