name: CakePHP CI

on: [pull_request]

jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.3']
        db-type: [sqlite, mysql, postgres]
    name: PHP ${{ matrix.php-version }} & ${{ matrix.db-type }}

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
      memcached:
        image: memcached
        ports:
          - 11211/tcp
      postgres:
        image: postgres
        ports:
          - 5432/tcp

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install packages
      run: |
        # Without removing php-fpm extensions installation fails for some reason
        sudo apt remove php${{ matrix.php-version }}-fpm
        sudo apt install php${{ matrix.php-version }}-intl
        sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
        sudo update-alternatives --set phar /usr/bin/phar${{ matrix.php-version }}
        sudo update-alternatives --set phar.phar /usr/bin/phar.phar${{ matrix.php-version }}
        sudo phpdismod xdebug

        sudo locale-gen da_DK

        if [[ ${{ matrix.php-version }} == '7.2' ]]; then sudo apt install php-pcov; fi

    - name: Set ENV vars
      run: |
        if [[ ${{ matrix.db-type }} == 'sqlite' ]]; then export DB_DSN='sqlite:///:memory:'; fi
        if [[ ${{ matrix.db-type }} == 'mysql' ]]; then export DB_DSN='mysql://root@127.0.0.1/cakephp_test?init[]=SET sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"'; fi
        if [[ ${{ matrix.db-type }} == 'postgres' ]]; then export DB_DSN='postgres://postgres@127.0.0.1:${{ job.services.postgres.ports['5432'] }}/cakephp_test'; fi

    - name: composer install
      run: composer install

    - name: Run PHPUnit
      env:
        REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
        MEMCACHED_PORT: ${{ job.services.memcached.ports['11211'] }}
      run: |
        if [[ ${{ matrix.php-version }} == '7.2' ]]; then
          # Setting CODECOVERAGE is necessary to skip memory usage tests
          CODECOVERAGE=1 vendor/bin/phpunit --coverage-clover=clover.xml
        else
          vendor/bin/phpunit
        fi

    - name: Submit code coverage data
      run: |
        if [[ ${{ matrix.php-version }} == '7.2' ]]; then
          wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
          chmod +x php-coveralls.phar
          ./php-coveralls.phar
        fi

  coding-standard:
    name: Coding Standard
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup PHP
      run: |
        # Without removing php-fpm extensions installation fails for some reason
        sudo apt remove php7.2-fpm
        sudo apt install php7.2-intl
        sudo update-alternatives --set php /usr/bin/php7.2
        sudo update-alternatives --set phar /usr/bin/phar7.2
        sudo update-alternatives --set phar.phar /usr/bin/phar.phar7.2
        sudo phpdismod xdebug

    - name: composer install
      run: composer stan-setup

    - name: Run PHP CodeSniffer
      run: composer cs-check

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup PHP
      run: |
        # Without removing php-fpm extensions installation fails for some reason
        sudo apt remove php7.2-fpm
        sudo apt install php7.2-intl
        sudo update-alternatives --set php /usr/bin/php7.2
        sudo update-alternatives --set phar /usr/bin/phar7.2
        sudo update-alternatives --set phar.phar /usr/bin/phar.phar7.2
        sudo phpdismod xdebug

    - name: composer install
      run: composer stan-setup

    - name: Run psalm
      run: vendor/bin/psalm.phar --show-info=false

    - name: Run phpstan
      run: vendor/bin/phpstan.phar analyse src/
